/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Youtube = {
  _type: "youtube";
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type InnerblockContent = Array<
  | ({
      _key: string;
    } & StyledBlock)
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type AlbumReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "album";
};

export type StyledBlock = {
  _type: "styledBlock";
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "blockquote" | "justify" | "center";
  listItem?: "bullet" | "number";
  markDefs?: Array<
    | {
        type?:
          | "underline"
          | "box"
          | "highlight"
          | "strike-through"
          | "crossed-off"
          | "brackets"
          | "circle";
        color?: Color;
        animate?: boolean;
        order?: number;
        _type: "rough";
        _key: string;
      }
    | {
        href?: string;
        _type: "link";
        _key: string;
      }
    | {
        reference?: PostReference | PageReference | AlbumReference;
        _type: "internalLink";
        _key: string;
      }
  >;
  level?: number;
};

export type BlockContent = Array<
  | ({
      _key: string;
    } & StyledBlock)
  | {
      leftCol?: InnerblockContent;
      rightCol?: InnerblockContent;
      _type: "layout-col-2";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Youtube)
  | ({
      _key: string;
    } & PostReference)
  | ({
      _key: string;
    } & AlbumReference)
  | ({
      _key: string;
    } & AlbumReference)
>;

export type PageList = {
  _id: string;
  _type: "pageList";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  showHome?: boolean;
  pages?: Array<
    | ({
        _key: string;
      } & PageReference)
    | {
        title?: string;
        title_fr?: string;
        slug?: string;
        slug_fr?: string;
        _type: "hardcodedPage";
        _key: string;
      }
  >;
};

export type Colors = {
  _type: "colors";
  name?: string;
  primary?: Color;
  secondary?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  id?: string;
};

export type SocialLink = {
  _type: "socialLink";
  type?:
    | "instagram"
    | "facebook"
    | "youtube"
    | "twitter"
    | "twitch"
    | "linkedin"
    | "pinterest"
    | "snapchat"
    | "tiktok"
    | "reddit"
    | "tumblr"
    | "whatsapp"
    | "telegram"
    | "discord"
    | "medium"
    | "flickr"
    | "vimeo"
    | "soundcloud"
    | "spotify"
    | "behance"
    | "dribbble";
  name?: string;
  url?: string;
};

export type CustomThemeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customTheme";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  siteTitle?: string;
  description?: string;
  author?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  customFont?:
    | "raleway"
    | "montserrat"
    | "inter"
    | "nunito"
    | "comfortaa"
    | "rokkitt"
    | "josefinSans"
    | "dmSans"
    | "spaceGrotesk"
    | "dosis"
    | "libreFranklin"
    | "vollkorn";
  customDisplayFont?:
    | "raleway"
    | "montserrat"
    | "inter"
    | "nunito"
    | "comfortaa"
    | "rokkitt"
    | "josefinSans"
    | "dmSans"
    | "spaceGrotesk"
    | "dosis"
    | "libreFranklin"
    | "vollkorn";
  darkThemeName?:
    | "mytheme"
    | "dark"
    | "synthwave"
    | "dracula"
    | "black"
    | "night"
    | "dim"
    | "sunset"
    | "business";
  lightThemeName?:
    | "light"
    | "autumn"
    | "retro"
    | "cupcake"
    | "emerald"
    | "lofi"
    | "garden"
    | "cmyk"
    | "winter"
    | "nord"
    | "cyberpunk";
  customDarkTheme?: CustomThemeReference;
  customLightTheme?: CustomThemeReference;
};

export type CustomTheme = {
  _id: string;
  _type: "customTheme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  p?: Color;
  pc?: Color;
  s?: Color;
  sc?: Color;
  a?: Color;
  ac?: Color;
  n?: Color;
  nc?: Color;
  b1?: Color;
  b2?: Color;
  b3?: Color;
  bc?: Color;
  in?: Color;
  su?: Color;
  wa?: Color;
  er?: Color;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PageReference;
  language?: string;
};

export type InternationalizedArraySlugValue = {
  _type: "internationalizedArraySlugValue";
  value?: Slug;
  language?: string;
};

export type InternationalizedArrayBlockContentValue = {
  _type: "internationalizedArrayBlockContentValue";
  value?: BlockContent;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type InternationalizedArraySlug = Array<
  {
    _key: string;
  } & InternationalizedArraySlugValue
>;

export type InternationalizedArrayBlockContent = Array<
  {
    _key: string;
  } & InternationalizedArrayBlockContentValue
>;

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  slug_fr?: Slug;
  author?: {
    name?: string;
    id?: string;
    _type: "author";
  };
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tags?: Array<string>;
  publishDate?: string;
  postContent?: InternationalizedArrayBlockContent;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  content?: BlockContent;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Album = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  albumName?: string;
  slug?: Slug;
  category?: CategoryReference;
  publishDate?: string;
  albumContent?: InternationalizedArrayBlockContent;
  display?: "rows" | "columns" | "masonry";
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  columns?: 2 | 3 | 4 | 5 | 6;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    featured?: boolean;
    alt?: string;
    decorative?: boolean;
    title?: string;
    description?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    >;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categoryName?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Youtube
  | SanityImageAssetReference
  | InnerblockContent
  | PostReference
  | PageReference
  | AlbumReference
  | StyledBlock
  | BlockContent
  | PageList
  | Colors
  | Color
  | Author
  | SocialLink
  | CustomThemeReference
  | SiteSettings
  | CustomTheme
  | MediaTag
  | Slug
  | RgbaColor
  | HsvaColor
  | HslaColor
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | InternationalizedArraySlugValue
  | InternationalizedArrayBlockContentValue
  | InternationalizedArrayStringValue
  | InternationalizedArraySlug
  | InternationalizedArrayBlockContent
  | Post
  | Page
  | CategoryReference
  | Album
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | InternationalizedArrayString
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_METADATA_QUERY
// Query: *[_type == "siteSettings"][0]{  siteTitle,  description,  author,  customFont,  customDisplayFont,  themes{darkThemeName, lightThemeName},  "customThemes": {    "darkTheme": customDarkTheme->{p{hex},pc{hex},s{hex},sc{hex},a{hex},ac{hex},n{hex},nc{hex},b1{hex},b2{hex},b3{hex},bc{hex},in{hex},su{hex},wa{hex},er{hex}},    "lightTheme": customLightTheme->{p{hex},pc{hex},s{hex},sc{hex},a{hex},ac{hex},n{hex},nc{hex},b1{hex},b2{hex},b3{hex},bc{hex},in{hex},su{hex},wa{hex},er{hex}}  },  socialLinks[]{name, type, url}}
export type SITE_METADATA_QUERY_RESULT = {
  siteTitle: string | null;
  description: string | null;
  author: string | null;
  customFont:
    | "comfortaa"
    | "dmSans"
    | "dosis"
    | "inter"
    | "josefinSans"
    | "libreFranklin"
    | "montserrat"
    | "nunito"
    | "raleway"
    | "rokkitt"
    | "spaceGrotesk"
    | "vollkorn"
    | null;
  customDisplayFont:
    | "comfortaa"
    | "dmSans"
    | "dosis"
    | "inter"
    | "josefinSans"
    | "libreFranklin"
    | "montserrat"
    | "nunito"
    | "raleway"
    | "rokkitt"
    | "spaceGrotesk"
    | "vollkorn"
    | null;
  themes: null;
  customThemes: {
    darkTheme: {
      p: {
        hex: string | null;
      } | null;
      pc: {
        hex: string | null;
      } | null;
      s: {
        hex: string | null;
      } | null;
      sc: {
        hex: string | null;
      } | null;
      a: {
        hex: string | null;
      } | null;
      ac: {
        hex: string | null;
      } | null;
      n: {
        hex: string | null;
      } | null;
      nc: {
        hex: string | null;
      } | null;
      b1: {
        hex: string | null;
      } | null;
      b2: {
        hex: string | null;
      } | null;
      b3: {
        hex: string | null;
      } | null;
      bc: {
        hex: string | null;
      } | null;
      in: {
        hex: string | null;
      } | null;
      su: {
        hex: string | null;
      } | null;
      wa: {
        hex: string | null;
      } | null;
      er: {
        hex: string | null;
      } | null;
    } | null;
    lightTheme: {
      p: {
        hex: string | null;
      } | null;
      pc: {
        hex: string | null;
      } | null;
      s: {
        hex: string | null;
      } | null;
      sc: {
        hex: string | null;
      } | null;
      a: {
        hex: string | null;
      } | null;
      ac: {
        hex: string | null;
      } | null;
      n: {
        hex: string | null;
      } | null;
      nc: {
        hex: string | null;
      } | null;
      b1: {
        hex: string | null;
      } | null;
      b2: {
        hex: string | null;
      } | null;
      b3: {
        hex: string | null;
      } | null;
      bc: {
        hex: string | null;
      } | null;
      in: {
        hex: string | null;
      } | null;
      su: {
        hex: string | null;
      } | null;
      wa: {
        hex: string | null;
      } | null;
      er: {
        hex: string | null;
      } | null;
    } | null;
  };
  socialLinks: Array<{
    name: string | null;
    type:
      | "behance"
      | "discord"
      | "dribbble"
      | "facebook"
      | "flickr"
      | "instagram"
      | "linkedin"
      | "medium"
      | "pinterest"
      | "reddit"
      | "snapchat"
      | "soundcloud"
      | "spotify"
      | "telegram"
      | "tiktok"
      | "tumblr"
      | "twitch"
      | "twitter"
      | "vimeo"
      | "whatsapp"
      | "youtube"
      | null;
    url: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HEADER_QUERY
// Query: *[_type == "pageList" && defined(pages)][0]{  showHome,  pages[]->{    title,    title_fr,    "slug": slug.current,    "slug_fr": slug_fr.current,    "_translations": *[_type == "translation.metadata" && references(^._id)][0]{      "_translations": translations[].value->{language, title, slug}    }  }}
export type HEADER_QUERY_RESULT = {
  showHome: boolean | null;
  pages: Array<{
    title: string | null;
    title_fr: null;
    slug: string | null;
    slug_fr: null;
    _translations: {
      _translations: Array<{
        language: string | null;
        title: string | null;
        slug: Slug | null;
      } | null> | null;
    } | null;
  } | null>;
} | null;

// Source: src/sanity/queries.ts
// Variable: CATEGORY_INDEX_QUERY
// Query: *[_type == "category" && count(*[_type == "album" && references(^._id)]) > 0]{  _id,  categoryName,  slug,  "coverImage": coverImage{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}},  "albums": *[_type == "album" && references(^._id)] | order(coalesce(publishDate, "") desc){    _id,    albumName,    slug,    "images": images[0...1]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}},    "cover": images[0]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}}  }}
export type CATEGORY_INDEX_QUERY_RESULT = Array<{
  _id: string;
  categoryName: string | null;
  slug: Slug | null;
  coverImage: {
    _key: null;
    _type: "image";
    alt: null;
    asset: SanityImageAssetReference | null;
    description: null;
    featured: null;
    title: null;
    placeholders: {
      metadata: {
        lqip: string | null;
      };
    };
  } | null;
  albums: Array<{
    _id: string;
    albumName: string | null;
    slug: Slug | null;
    images: Array<{
      _key: string;
      _type: "image";
      alt: string | null;
      asset: SanityImageAssetReference | null;
      description: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          }
      > | null;
      featured: boolean | null;
      title: string | null;
      placeholders: {
        metadata: {
          lqip: string | null;
        };
      };
    }> | null;
    cover: {
      _key: string;
      _type: "image";
      alt: string | null;
      asset: SanityImageAssetReference | null;
      description: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          }
      > | null;
      featured: boolean | null;
      title: string | null;
      placeholders: {
        metadata: {
          lqip: string | null;
        };
      };
    } | null;
  }>;
}>;

// Source: src/sanity/queries.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "album" && category->slug.current == $slug] | order(coalesce(publishDate, "") desc){  _id,  albumName,  slug,  "images": images[]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}}}
export type CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  albumName: string | null;
  slug: Slug | null;
  images: Array<{
    _key: string;
    _type: "image";
    alt: string | null;
    asset: SanityImageAssetReference | null;
    description: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    > | null;
    featured: boolean | null;
    title: string | null;
    placeholders: {
      metadata: {
        lqip: string | null;
      };
    };
  }> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)]{"slug": slug.current}
export type CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ALBUM_QUERY
// Query: *[_type == "album" && slug.current == $slug][0]{  _id,  albumName,  slug,  display,  columns,  "description": albumContent[_key == $locale][0].value,  "category": category->{categoryName, slug},  "images": images[]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}}}
export type ALBUM_QUERY_RESULT = {
  _id: string;
  albumName: string | null;
  slug: Slug | null;
  display: "columns" | "masonry" | "rows" | null;
  columns: 2 | 3 | 4 | 5 | 6 | null;
  description: BlockContent | null;
  category: {
    categoryName: string | null;
    slug: Slug | null;
  } | null;
  images: Array<{
    _key: string;
    _type: "image";
    alt: string | null;
    asset: SanityImageAssetReference | null;
    description: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    > | null;
    featured: boolean | null;
    title: string | null;
    placeholders: {
      metadata: {
        lqip: string | null;
      };
    };
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: ALBUM_SLUGS_QUERY
// Query: *[_type == "album" && defined(slug.current)]{"slug": slug.current}
export type ALBUM_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ALL_IMAGES_QUERY
// Query: *[_type == "album"].images[]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}}
export type ALL_IMAGES_QUERY_RESULT = Array<{
  _key: string;
  _type: "image";
  alt: string | null;
  asset: SanityImageAssetReference | null;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  featured: boolean | null;
  title: string | null;
  placeholders: {
    metadata: {
      lqip: string | null;
    };
  };
} | null>;

// Source: src/sanity/queries.ts
// Variable: FEATURED_IMAGES_QUERY
// Query: *[_type == "album"].images[featured == true]{  _key,  _type,  alt,  asset,  description,  featured,  title,  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}}
export type FEATURED_IMAGES_QUERY_RESULT = Array<{
  _key: string;
  _type: "image";
  alt: string | null;
  asset: SanityImageAssetReference | null;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  featured: true;
  title: string | null;
  placeholders: {
    metadata: {
      lqip: string | null;
    };
  };
} | null>;

// Source: src/sanity/queries.ts
// Variable: POST_LIST_QUERY
// Query: {  "posts": *[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]    | order(publishDate desc) [0...$limit] {  _id,  publishDate,  coverImage,  "slug": select(    $locale == "fr" => coalesce(slug_fr, slug),    coalesce(slug, slug_fr)  ),  "title": title[_key == $locale][0].value,  "blurDataURL": coverImage.asset->metadata.lqip,  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."},  "totalCount": count(*[_type == "post" && (defined(slug.current) || defined(slug_fr.current))])}
export type POST_LIST_QUERY_RESULT = {
  posts: Array<{
    _id: string;
    publishDate: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    slug: Slug | null;
    title: string | null;
    blurDataURL: string | null;
    excerpt: string;
  }>;
  totalCount: number;
};

// Source: src/sanity/queries.ts
// Variable: POST_CURSOR_QUERY
// Query: *[_type == "post" && (defined(slug.current) || defined(slug_fr.current)) &&  (!defined($cursor) || publishDate < $cursor)]  | order(publishDate desc) [0...$limit] {  _id,  publishDate,  coverImage,  "slug": select(    $locale == "fr" => coalesce(slug_fr, slug),    coalesce(slug, slug_fr)  ),  "title": title[_key == $locale][0].value,  "blurDataURL": coverImage.asset->metadata.lqip,  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."}
export type POST_CURSOR_QUERY_RESULT = Array<{
  _id: string;
  publishDate: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  slug: Slug | null;
  title: string | null;
  blurDataURL: string | null;
  excerpt: string;
}>;

// Source: src/sanity/queries.ts
// Variable: LATEST_POST_QUERY
// Query: *[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]  | order(publishDate desc) [0] {  _id,  publishDate,  coverImage,  "slug": select(    $locale == "fr" => coalesce(slug_fr, slug),    coalesce(slug, slug_fr)  ),  "title": title[_key == $locale][0].value,  "blurDataURL": coverImage.asset->metadata.lqip,  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."}
export type LATEST_POST_QUERY_RESULT = {
  _id: string;
  publishDate: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  slug: Slug | null;
  title: string | null;
  blurDataURL: string | null;
  excerpt: string;
} | null;

// Source: src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && (slug.current == $slug || slug_fr.current == $slug)][0]{  "current": {    _id,    publishDate,    coverImage,    "slug": select($locale == "fr" => coalesce(slug_fr, slug), coalesce(slug, slug_fr)),    "title": title[_key == $locale][0].value,    "postContent": postContent[_key == $locale][0]  },  "previous": *[_type == "post" && publishDate < ^.publishDate] | order(publishDate desc)[0] {  _id,  publishDate,  coverImage,  "slug": select(    $locale == "fr" => coalesce(slug_fr, slug),    coalesce(slug, slug_fr)  ),  "title": title[_key == $locale][0].value,  "blurDataURL": coverImage.asset->metadata.lqip,  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."},  "next": *[_type == "post" && publishDate > ^.publishDate] | order(publishDate asc)[0] {  _id,  publishDate,  coverImage,  "slug": select(    $locale == "fr" => coalesce(slug_fr, slug),    coalesce(slug, slug_fr)  ),  "title": title[_key == $locale][0].value,  "blurDataURL": coverImage.asset->metadata.lqip,  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."}}
export type POST_QUERY_RESULT = {
  current: {
    _id: string;
    publishDate: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    slug: Slug | null;
    title: string | null;
    postContent:
      | ({
          _key: string;
        } & InternationalizedArrayBlockContentValue)
      | null;
  };
  previous: {
    _id: string;
    publishDate: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    slug: Slug | null;
    title: string | null;
    blurDataURL: string | null;
    excerpt: string;
  } | null;
  next: {
    _id: string;
    publishDate: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    slug: Slug | null;
    title: string | null;
    blurDataURL: string | null;
    excerpt: string;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]{  "slug": slug.current,  "slugFr": slug_fr.current}
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  slugFr: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug && language == $locale][0]{  _id,  title,  slug,  language,  content,  "_translations": *[_type == "translation.metadata" && references(^._id)].translations[].value->{    language,    title,    slug  }}
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  language: string | null;
  content: BlockContent | null;
  _translations: Array<{
    language: string | null;
    title: string | null;
    slug: Slug | null;
  } | null>;
} | null;

// Source: src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{language, "slug": slug.current}
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: OG_POST_IMAGE_QUERY
// Query: *[_type == "post" && (slug.current == $slug || slug_fr.current == $slug)][0].coverImage
export type OG_POST_IMAGE_QUERY_RESULT = {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
} | null;

// Source: src/sanity/queries.ts
// Variable: OG_ALBUM_IMAGE_QUERY
// Query: *[_type == "album" && slug.current == $slug][0].images[0]
export type OG_ALBUM_IMAGE_QUERY_RESULT = {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  featured?: boolean;
  alt?: string;
  decorative?: boolean;
  title?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  _type: "image";
  _key: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  siteTitle,\n  description,\n  author,\n  customFont,\n  customDisplayFont,\n  themes{darkThemeName, lightThemeName},\n  "customThemes": {\n    "darkTheme": customDarkTheme->{p{hex},pc{hex},s{hex},sc{hex},a{hex},ac{hex},n{hex},nc{hex},b1{hex},b2{hex},b3{hex},bc{hex},in{hex},su{hex},wa{hex},er{hex}},\n    "lightTheme": customLightTheme->{p{hex},pc{hex},s{hex},sc{hex},a{hex},ac{hex},n{hex},nc{hex},b1{hex},b2{hex},b3{hex},bc{hex},in{hex},su{hex},wa{hex},er{hex}}\n  },\n  socialLinks[]{name, type, url}\n}': SITE_METADATA_QUERY_RESULT;
    '*[_type == "pageList" && defined(pages)][0]{\n  showHome,\n  pages[]->{\n    title,\n    title_fr,\n    "slug": slug.current,\n    "slug_fr": slug_fr.current,\n    "_translations": *[_type == "translation.metadata" && references(^._id)][0]{\n      "_translations": translations[].value->{language, title, slug}\n    }\n  }\n}': HEADER_QUERY_RESULT;
    '\n*[_type == "category" && count(*[_type == "album" && references(^._id)]) > 0]{\n  _id,\n  categoryName,\n  slug,\n  "coverImage": coverImage{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n},\n  "albums": *[_type == "album" && references(^._id)] | order(coalesce(publishDate, "") desc){\n    _id,\n    albumName,\n    slug,\n    "images": images[0...1]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n},\n    "cover": images[0]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n}\n  }\n}': CATEGORY_INDEX_QUERY_RESULT;
    '\n*[_type == "album" && category->slug.current == $slug] | order(coalesce(publishDate, "") desc){\n  _id,\n  albumName,\n  slug,\n  "images": images[]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n}\n}': CATEGORY_QUERY_RESULT;
    '\n*[_type == "category" && defined(slug.current)]{"slug": slug.current}\n': CATEGORY_SLUGS_QUERY_RESULT;
    '\n*[_type == "album" && slug.current == $slug][0]{\n  _id,\n  albumName,\n  slug,\n  display,\n  columns,\n  "description": albumContent[_key == $locale][0].value,\n  "category": category->{categoryName, slug},\n  "images": images[]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n}\n}': ALBUM_QUERY_RESULT;
    '\n*[_type == "album" && defined(slug.current)]{"slug": slug.current}\n': ALBUM_SLUGS_QUERY_RESULT;
    '\n*[_type == "album"].images[]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n}\n': ALL_IMAGES_QUERY_RESULT;
    '\n*[_type == "album"].images[featured == true]{\n  _key,\n  _type,\n  alt,\n  asset,\n  description,\n  featured,\n  title,\n  "placeholders": {"metadata": {"lqip": asset->metadata.lqip}}\n}\n': FEATURED_IMAGES_QUERY_RESULT;
    '{\n  "posts": *[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]\n    | order(publishDate desc) [0...$limit] {\n  _id,\n  publishDate,\n  coverImage,\n  "slug": select(\n    $locale == "fr" => coalesce(slug_fr, slug),\n    coalesce(slug, slug_fr)\n  ),\n  "title": title[_key == $locale][0].value,\n  "blurDataURL": coverImage.asset->metadata.lqip,\n  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."\n},\n  "totalCount": count(*[_type == "post" && (defined(slug.current) || defined(slug_fr.current))])\n}': POST_LIST_QUERY_RESULT;
    '\n*[_type == "post" && (defined(slug.current) || defined(slug_fr.current)) &&\n  (!defined($cursor) || publishDate < $cursor)]\n  | order(publishDate desc) [0...$limit] {\n  _id,\n  publishDate,\n  coverImage,\n  "slug": select(\n    $locale == "fr" => coalesce(slug_fr, slug),\n    coalesce(slug, slug_fr)\n  ),\n  "title": title[_key == $locale][0].value,\n  "blurDataURL": coverImage.asset->metadata.lqip,\n  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."\n}\n': POST_CURSOR_QUERY_RESULT;
    '\n*[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]\n  | order(publishDate desc) [0] {\n  _id,\n  publishDate,\n  coverImage,\n  "slug": select(\n    $locale == "fr" => coalesce(slug_fr, slug),\n    coalesce(slug, slug_fr)\n  ),\n  "title": title[_key == $locale][0].value,\n  "blurDataURL": coverImage.asset->metadata.lqip,\n  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."\n}\n': LATEST_POST_QUERY_RESULT;
    '\n*[_type == "post" && (slug.current == $slug || slug_fr.current == $slug)][0]{\n  "current": {\n    _id,\n    publishDate,\n    coverImage,\n    "slug": select($locale == "fr" => coalesce(slug_fr, slug), coalesce(slug, slug_fr)),\n    "title": title[_key == $locale][0].value,\n    "postContent": postContent[_key == $locale][0]\n  },\n  "previous": *[_type == "post" && publishDate < ^.publishDate] | order(publishDate desc)[0] {\n  _id,\n  publishDate,\n  coverImage,\n  "slug": select(\n    $locale == "fr" => coalesce(slug_fr, slug),\n    coalesce(slug, slug_fr)\n  ),\n  "title": title[_key == $locale][0].value,\n  "blurDataURL": coverImage.asset->metadata.lqip,\n  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."\n},\n  "next": *[_type == "post" && publishDate > ^.publishDate] | order(publishDate asc)[0] {\n  _id,\n  publishDate,\n  coverImage,\n  "slug": select(\n    $locale == "fr" => coalesce(slug_fr, slug),\n    coalesce(slug, slug_fr)\n  ),\n  "title": title[_key == $locale][0].value,\n  "blurDataURL": coverImage.asset->metadata.lqip,\n  "excerpt": array::join(string::split(pt::text(postContent[_key == $locale][0].value), "")[0...255], "") + "..."\n}\n}': POST_QUERY_RESULT;
    '\n*[_type == "post" && (defined(slug.current) || defined(slug_fr.current))]{\n  "slug": slug.current,\n  "slugFr": slug_fr.current\n}': POST_SLUGS_QUERY_RESULT;
    '\n*[_type == "page" && slug.current == $slug && language == $locale][0]{\n  _id,\n  title,\n  slug,\n  language,\n  content,\n  "_translations": *[_type == "translation.metadata" && references(^._id)].translations[].value->{\n    language,\n    title,\n    slug\n  }\n}': PAGE_QUERY_RESULT;
    '\n*[_type == "page" && defined(slug.current)]{language, "slug": slug.current}\n': PAGE_SLUGS_QUERY_RESULT;
    '\n*[_type == "post" && (slug.current == $slug || slug_fr.current == $slug)][0].coverImage\n': OG_POST_IMAGE_QUERY_RESULT;
    '\n*[_type == "album" && slug.current == $slug][0].images[0]\n': OG_ALBUM_IMAGE_QUERY_RESULT;
  }
}
